- name: Install Docker
  command: amazon-linux-extras install docker -y
  become: yes

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes  