- name: Download sqlite {{ sqlite_version }}
  get_url:
    url: http://www.sqlite.org/sqlite-autoconf-{{sqlite_version}}.tar.gz
    dest: "sqlite-autoconf-{{sqlite_version}}.tar.gz"

- name: Unarchive Sqlite {{ sqlite_version }}
  ansible.builtin.unarchive:
    src: "sqlite-autoconf-{{sqlite_version}}.tar.gz"
    dest: "{{sqlite_install_dir}}"
    creates: "{{sqlite_install_dir}}/bin"
    extra_opts: [--strip-components=1]
    owner: "{{ app_user_name }}"
    group: "{{ app_group_name }}"     
    remote_src: yes

- name: Running ./configure for Sqlite
  command: "./configure  --prefix={{sqlite_install_dir}} >configure.log 2>&1"
  args: 
    chdir: "{{ sqlite_install_dir }}"

- name: Running "make" for Sqlite
  command: make >make.log 2>&1
  args: 
    chdir: "{{sqlite_install_dir}}"

- name: Running "make install" for Sqlite
  command: make install >makeinstall.log 2>&1
  args: 
    chdir: "{{sqlite_install_dir}}"
  become: yes

- name: Making sure sqlite is installed
  shell: "{{ sqlite_cmd_path }}/sqlite3 --version"
  register: sqlite_op
  failed_when: "sqlite_op.rc != 0" 
