- name: Install epel repo
  shell: |
    amazon-linux-extras install epel -y
    yum-config-manager --enable epel
  become: yes

- name: Install R packages
  yum:
    name: "{{ r_packages }}"
    state: latest
  become: yes

- name: Install R4
  command: amazon-linux-extras install R4
  become: yes

- name: Install r - packages
  command: >-
    Rscript --slave --no-save --no-restore-history -e "
    if (! ('{{ item }}' %in% installed.packages()[,'Package'])) {
      install.packages(pkgs='{{ item }}', repos=c('http://ftp.heanet.ie/mirrors/cran.r-project.org/'));
      print('Added');
    } else {
      print('Already installed');
    }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  loop:
    - tidyverse
    - BiocManager
    - Seurat

- name: Install BiocManager - r - packages
  command: >-
    Rscript --slave --no-save --no-restore-history -e "
      if (! ('DESeq2' %in% installed.packages()[,'Package'])) {
        BiocManager::install(pkgs='DESeq2');
        print('Added');
      } else {
        print('Already installed');
      }"
  register: B_result
  failed_when: "B_result.rc != 0 or 'had non-zero exit status' in B_result.stderr"
  changed_when: "'Added' in B_result.stdout"
